default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:

development:
  <<: *default
  database: ruby_internship_development
  username: postgres
  password:

test:
  <<: *default
  database: ruby_internship_test
  username: postgres
  password:

production:
  <<: *default
  database: ruby_internship_production
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
