# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1cfe0711d7bacbe2de628e31240fb7261afdd376dab349fecec46a10f65254ad77875b5d2ca3f0150e91098a1b2db48cbf9bc901d60030e122ebf3b8ac31554

test:
  secret_key_base: ed48501e79aeefbfaeb718bbf0d6485a91c57ae61b96d57e385502ae7da9dccb04b6d88e417c64ee9652800f447dbfcb4bd8514ccb6663b9da5dcedb1f36c871

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
